export const KHMER_TOKEN_ADDRESS = "6nmsoBwQGHKgx33qfwanC84g49QKmygmHHuexZHcsiN2";

export const KHMER_TOKEN_TRANSFER_COMPUTE_UNITS = 10000;
export const TOKEN_TRANSFER_COMPUTE_UNIT_MICRO_LAMPORTS = 100000;
